# Use this in your UnturnedImages/config.yaml file
- Id: "39398-39399;39618-39619;39700-39712" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/3675250770/vehicles/{ItemId}.png" # The repository of the override.